stages:
  - stage: continuos-integration
    displayName: CI
    jobs:
    - job: buildjob
      displayName: buildjob  
      steps:
      - script: dotnet restore
        displayName: restore
      - script: dotnet build
        displayName: build
      - script: dotnet test
        displayName: test
      - script: dotnet publish
        displayName: publish